In [58]:


import numpy as np 

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(a.shape)
print(b.shape)
print(a.dtype)
print(a.ndim)
print(a.size)

(4,)
(4,)
int64
1
4


In [4]:
#'(4,)' is not ok for machine learning so we can use reshape

c = a.reshape((4,1))
c

array([[1],
       [2],
       [3],
       [4]])

In [5]:
print(c.shape)

(4, 1)


In [7]:
#prod should be size of the count of a ( a has 4 int )
d = a.reshape((2,2,1))
d.shape 

(2, 2, 1)

In [8]:
#sometimes we don't know how many int we have in this time we use -1 (which shape)
e = a.reshape((2,-1,1))
e.shape

(2, 2, 1)

In [9]:
#concatenate
a = np.array([2,3,4,5])
b = np.array([6,7,8,9])
c = np.concatenate((a,b))
c 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a = np.array([2,3,4,5])
b = np.array([6,7,8,9])
c = a * b 
print(c)
d = a + b 
print(d)

[12 21 32 45]
[ 8 10 12 14]


In [13]:
#data broadcasting
m = a+ 5
m

array([ 7,  8,  9, 10])

In [14]:
#or(data broadcasting)
m = np.array([10])
t = a + m
t

array([12, 13, 14, 15])

In [16]:
#select one part of one list
#slicing
a = np.array([2, 3, 4, 5, 6, 7, 8, 9])
b = a[1:7:2]
b

array([3, 5, 7])

In [17]:
a = np.array([2, 3, 4, 5, 6, 7, 8, 9])
b = a[a>3]
b 

array([4, 5, 6, 7, 8, 9])

In [22]:
a = np.array([2, 3, 4, 5, 6, 7, 8, 9])
b = np.sum(a)
c = np.max(a)
print(c)
print(b) 

9
44


In [23]:
#sort of the list
a = np.array([2, 3, 4, 5, 6, 7, 8, 9])
b = np.sort(a)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#building a list or matrix in a random way
a = np.random.randint(-100,100,(3,4))
b = np.random.random((3,6))
c = np.random.choice(['a','b','t'],size=2) #can have duplicated #replace =  false 
d = np.random.permutation([1,2,3,4]) #combine int in  a random way
print(a)
print('*' * 10)
print(b)
print('*' * 10)
print(c)
print('*' * 10)
print(d)


[[-43  56  87  -1]
 [-86 -18 -32  97]
 [-11  59  81 -19]]
**********
[[0.56891493 0.40579699 0.7012795  0.40282043 0.19414056 0.75762601]
 [0.51243626 0.22175709 0.15217499 0.44135061 0.44137643 0.97231683]
 [0.12125381 0.14414986 0.06104283 0.79898459 0.31410894 0.30942647]]
**********
['a' 'a']
**********
[3 2 1 4]


In [25]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
c #[[][]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
# hstack =  concatenate 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b)) #should be a tuple else error
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:

#normalize 
a = np.array([1,2,3,4])
mean_a = np.mean(a)
std = np.std(a)
print(std)
print(mean_a)

1.118033988749895
2.5


In [28]:
a = np.array([1,2,3,4])
std = np.std(a)
std 

np.float64(1.118033988749895)

In [31]:

print(np.arange(3.2,97.6,.21))

[ 3.2   3.41  3.62  3.83  4.04  4.25  4.46  4.67  4.88  5.09  5.3   5.51
  5.72  5.93  6.14  6.35  6.56  6.77  6.98  7.19  7.4   7.61  7.82  8.03
  8.24  8.45  8.66  8.87  9.08  9.29  9.5   9.71  9.92 10.13 10.34 10.55
 10.76 10.97 11.18 11.39 11.6  11.81 12.02 12.23 12.44 12.65 12.86 13.07
 13.28 13.49 13.7  13.91 14.12 14.33 14.54 14.75 14.96 15.17 15.38 15.59
 15.8  16.01 16.22 16.43 16.64 16.85 17.06 17.27 17.48 17.69 17.9  18.11
 18.32 18.53 18.74 18.95 19.16 19.37 19.58 19.79 20.   20.21 20.42 20.63
 20.84 21.05 21.26 21.47 21.68 21.89 22.1  22.31 22.52 22.73 22.94 23.15
 23.36 23.57 23.78 23.99 24.2  24.41 24.62 24.83 25.04 25.25 25.46 25.67
 25.88 26.09 26.3  26.51 26.72 26.93 27.14 27.35 27.56 27.77 27.98 28.19
 28.4  28.61 28.82 29.03 29.24 29.45 29.66 29.87 30.08 30.29 30.5  30.71
 30.92 31.13 31.34 31.55 31.76 31.97 32.18 32.39 32.6  32.81 33.02 33.23
 33.44 33.65 33.86 34.07 34.28 34.49 34.7  34.91 35.12 35.33 35.54 35.75
 35.96 36.17 36.38 36.59 36.8  37.01 37.22 37.43 37

In [32]:

print(np.linspace(0,20,6))

[ 0.  4.  8. 12. 16. 20.]


In [33]:
# 3 arrays 2 , which it is 4*2 with 0
print(np.zeros((3,2,4,2)))

[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [34]:
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [38]:
print(np.full((3,2,4,2),3))

[[[[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]]


 [[[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]]


 [[[3 3]
   [3 3]
   [3 3]
   [3 3]]

  [[3 3]
   [3 3]
   [3 3]
   [3 3]]]]


In [39]:
#dynamic
arr = np.array([[10,12,11],[17,14,19]])
print(np.full(arr.shape,7))
print('*' * 10)
print(np.full_like(arr,7))

[[7 7 7]
 [7 7 7]]
**********
[[7 7 7]
 [7 7 7]]


In [53]:
arr = np.array([[10,12,11],[17,14,19]])
print(np.prod(arr))
print(np.diff(arr))




5969040
[[ 2 -1]
 [-3  5]]


In [56]:
a = np.array([1,2,3,4,4,5,6,4])
np.unique(a,return_counts=True,return_index=True)

(array([1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 5, 6]),
 array([1, 1, 1, 3, 1, 1]))

In [62]:
# a = np.array([1,2,3,4,4,5,6,4],dtype=np.uint8)


x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x.T)
x.min()
x.argmin()

[[ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]
 [ 7 14]]


np.int64(0)

np.int64(0)

In [65]:
scors = np.array([8,9,12,20,19,1])
stats = np.array([0,0,1,1,1,0])
print(scors[stats==1])
print(np.where(stats==1))

[12 20 19]
(array([2, 3, 4]),)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [71]:

# turn to vector
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.ravel(x)
print(y)

[1 2 3 4 5 6]
